---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: fedora
    image: registry.fedoraproject.org/fedora:33
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
